on:
  push:
    branches:
      - main

jobs:
  deploy_source:
    name: build and deploy lambda
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies, Build application and Zip dist folder contents
        run: npm install && npx prisma generate --sql && tsc && npm run build-remove-prisma && npm run build-remove-primsa-debian && npm run build-zip
        env:
          DIRECT_URL: ${{ secrets.DIRECT_URL }}
          DATABASE_URL: ${{ secrets.DIRECT_URL }}
      - name: deploy zip to s3
        uses: hkusu/s3-upload-action@v2
        with:
          bucket-root: "recaps"
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-bucket: "brickd-tasker-zip"
          destination-dir: "/"
          file-path: "./bundle.zip"
      - name: deploy s3 zip to aws lambda
        uses: appleboy/lambda-action@v0.2.0
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: brickd-recaps
          s3_bucket: "brickd-tasker-zip"
          s3_key: "recaps/bundle.zip"
